const SET_INIT = "SET_INIT";
const SET_KOTS = "SET_KOTS";
const SET_PREFERENCES = "SET_PREFERENCES";
const SET_SETTINGS = "SET_SETTINGS";
const SET_ITEMS = "SET_ITEMS";
const SET_VENDORS="SET_VENDORS";
const SET_CLIENTS = "SET_CLIENTS";
const SET_CONTACTS = "SET_CONTACTS";
const SET_FAVOURITES = "SET_FAVOURITES";
const SET_COMPANY = "SET_COMPANY";
const SET_VOUCHERTYPE = "SET_VOUCHERTYPE";
const SET_VOUCHERITEMS = "SET_VOUCHERITEMS";
const SET_FAVOURITECLIENTS = "SET_FAVOURITECLIENTS";
const SET_FAVOURITEVENDORS = "SET_FAVOURITEVENDORS";
const UPDATE_VOUCHERITEMS = "UPDATE_VOUCHERITEMS";
const DELETE_VOUCHERITEMS = "DELETE_VOUCHERITEMS";
const SET_CLIENTPENDINGINVOICES = "SET_CLIENTPENDINGINVOICES";
const SET_VOUCHERSETTINGS = "SET_VOUCHERSETTINGS";
const RESET_VOUCHERITEMS = "RESET_VOUCHERITEMS";
const SET_FAVOURITEITEMS = "SET_FAVOURITEITEMS";
const SET_CONNECTION = 'SET_CONNECTION';
const SET_NOTIFY = 'SET_NOTIFY';

export {
    SET_INIT,
    SET_KOTS,
    SET_SETTINGS,
    SET_ITEMS,
    SET_VENDORS,
    SET_CLIENTS,
    SET_CONTACTS,
    SET_FAVOURITECLIENTS,
    SET_FAVOURITEVENDORS,
    SET_FAVOURITES,
    SET_CLIENTPENDINGINVOICES,
    SET_PREFERENCES,
    SET_CONNECTION,
    SET_NOTIFY,
    SET_VOUCHERSETTINGS,
    SET_VOUCHERTYPE,
    SET_VOUCHERITEMS,
    UPDATE_VOUCHERITEMS,
    DELETE_VOUCHERITEMS,
    RESET_VOUCHERITEMS,
    SET_FAVOURITEITEMS,
    SET_COMPANY
};
