const SET_DIALOG = "SET_DIALOG";
const SET_MODAL = "SET_MODAL";
const SET_BOTTOMSHEET = "SET_BOTTOMSHEET";
const SET_PAGESHEET = "SET_PAGESHEET";
const SET_ALERT = "SET_ALERT";
const SET_LOADER = "SET_LOADER";
const SET_TOKEN = "SET_TOKEN";

const TOGGLE_LOADER = "TOGGLE_LOADER";

export {
    SET_DIALOG,
    SET_TOKEN,
    SET_MODAL,
    SET_ALERT,
    SET_LOADER,
    SET_BOTTOMSHEET,
    SET_PAGESHEET,
    TOGGLE_LOADER
};
